const ALL_CATEGORIES: string[] = [
  // ── Classic / Broad ────────────────────────────
  'Animals',
  'Foods',
  'Countries',
  'Sports',
  'Colors',
  'Clothing',
  'Beverages',
  'Fruits',
  'Vegetables',
  'Occupations',
  'Languages',
  'Flowers',
  'Trees',
  'Insects',
  'Candy',
  'Toys',
  'Furniture',
  'Emotions',
  'Holidays',
  'Metals',
  'Gemstones',
  'Fabrics',
  'Currencies',
  'Spices',
  'Herbs',
  'Grains',
  'Nuts',
  'Seafood',
  'Pasta Shapes',
  'Sauces',
  'Soups',
  'Breads',

  // ── People & Characters ────────────────────────
  'A Boy\'s Name',
  'A Girl\'s Name',
  'A Baby Name',
  'A Pet Name',
  'Historical Figures',
  'Fictional Villains',
  'Cartoon Characters',
  'Superheroes',
  'Famous Scientists',
  'Rappers or Singers',
  'Actors/Actresses',
  'Disney Characters',
  'YouTubers',
  'Famous Athletes',
  'Comedians',
  'Famous Chefs',
  'Band Names',
  'Famous Duos',
  'Movie Characters',
  'TV Show Characters',
  'Book Characters',
  'Fictional Robots',
  'Famous Couples',
  'Nicknames',

  // ── Entertainment & Media ──────────────────────
  'TV Shows',
  'Movies',
  'Songs',
  'Video Games',
  'Books',
  'Board Games',
  'Anime Series',
  'Movie Franchises',
  'Card Games',
  'Podcasts',
  'Reality TV Shows',
  'Comedy Movies',
  'Horror Movies',
  'Action Movies',
  'Romantic Movies',
  'Kids Movies',
  'Song Titles',
  'Album Names',
  'TV Show Catchphrases',
  'Famous Movie Quotes',
  'Mobile Games',
  'Classic Arcade Games',
  'Sitcoms',
  'Documentaries',
  'Musicals',
  'Fairy Tales',

  // ── Places ─────────────────────────────────────
  'World Capitals',
  'Famous Landmarks',
  'Tourist Attractions',
  'Restaurants or Fast Food Chains',
  'Fictional Places',
  'National Parks',
  'Islands',
  'European Cities',
  'Asian Countries',
  'African Countries',
  'South American Countries',
  'Beach Towns',
  'Mountain Ranges',
  'Rivers',
  'Deserts',
  'Neighborhoods',
  'Amusement Parks',
  'Stadiums or Arenas',
  'Famous Streets',
  'Colleges or Universities',
  'Haunted Places',

  // ── Food & Drink ───────────────────────────────
  'Breakfast Foods',
  'Pizza Toppings',
  'Desserts',
  'Cocktails or Drinks',
  'Snack Foods',
  'Types of Cheese',
  'Ice Cream Flavors',
  'Foods You Eat With Your Hands',
  'Things You Grill',
  'Sandwich Fillings',
  'Salad Ingredients',
  'Baked Goods',
  'Comfort Foods',
  'Foods That Are Messy',
  'Sushi Rolls',
  'Types of Pizza',
  'Types of Cake',
  'Types of Cookies',
  'Condiments',
  'Things in a Smoothie',
  'Fast Food Menu Items',
  'Midnight Snacks',
  'Party Foods',
  'Food Trucks Serve',
  'Things You Dip',
  'Types of Coffee',
  'Types of Tea',
  'Milkshake Flavors',

  // ── School & Work ──────────────────────────────
  'School Subjects',
  'College Majors',
  'Reasons to Call in Sick',
  'Things Your Boss Would Say',
  'Things You Procrastinate On',
  'Things in a Classroom',
  'School Supplies',
  'After-School Activities',
  'Things Teachers Say',
  'Homework Excuses',
  'Office Supplies',
  'Meeting Topics',
  'Things on a Resume',
  'Side Hustles',

  // ── Adjective / Characteristic ─────────────────
  'Things That Are Red',
  'Things That Are Blue',
  'Things That Are Green',
  'Things That Are Yellow',
  'Things That Are Expensive',
  'Things That Are Tiny',
  'Things That Are Huge',
  'Things That Smell Bad',
  'Things That Smell Good',
  'Things That Are Scary',
  'Things That Glow',
  'Things That Are Overrated',
  'Things That Are Addictive',
  'Things That Are Crunchy',
  'Things That Are Soft',
  'Things That Are Loud',
  'Things That Are Quiet',
  'Things That Are Fast',
  'Things That Are Slow',
  'Things That Are Sticky',
  'Things That Are Slippery',
  'Things That Are Heavy',
  'Things That Are Fragile',
  'Things That Are Round',
  'Things That Are Spicy',
  'Things That Are Sweet',
  'Things That Are Cold',
  'Things That Are Hot',
  'Things That Are Free',
  'Things That Are Annoying',
  'Things That Are Relaxing',
  'Things That Are Nostalgic',
  'Things That Are Cute',
  'Things That Are Shiny',
  'Things That Are Old-Fashioned',

  // ── Action / Experience ────────────────────────
  'Excuses for Being Late',
  'Bad Habits',
  'Hobbies',
  'Things You\'re Afraid Of',
  'Things You Do Every Day',
  'Things That Make You Laugh',
  'Things That Make You Cry',
  'Things You Yell',
  'Things You Whisper',
  'Things You Google at 3 AM',
  'Things That Ruin a Date',
  'Party Fouls',
  'Things You Pretend to Like',
  'Things That Go Wrong on Vacation',
  'Compliments',
  'Things Kids Say',
  'Things You Do When Nobody\'s Watching',
  'Things That Make You Nervous',
  'Things You\'d Do With a Million Dollars',
  'Things You Say to a Dog',
  'Things You Say When You\'re Lost',
  'Things You Do on a Snow Day',
  'Things You Do at a Party',
  'Things You Do Before Bed',
  'Things You Do on a Lazy Sunday',
  'First Date Activities',
  'Things You Do on Your Birthday',
  'Things You Do When the Wi-Fi Goes Out',
  'Things You Forget',
  'Things That Make You Smile',
  'Things You Collect',
  'Bucket List Items',
  'Things You Do in the Car',
  'Things You Do at the Beach',
  'Summer Activities',
  'Winter Activities',
  'Childhood Games',
  'Dare Ideas',
  'Things That Keep You Up at Night',
  'New Year\'s Resolutions',
  'Things You\'d Bring to a Deserted Island',
  'Weird Talents',
  'Things That Happen at Family Gatherings',
  'Road Trip Activities',
  'Things You Wait in Line For',
  'Guilty Pleasures',

  // ── Brands & Products ──────────────────────────
  'Brands',
  'Car Brands or Models',
  'Apps on Your Phone',
  'Cereal Brands',
  'Shoe Brands',
  'Clothing Brands',
  'Tech Companies',
  'Soda Brands',
  'Candy Bars',
  'Chip Flavors',
  'Perfume or Cologne Brands',
  'Makeup Brands',
  'Video Game Consoles',
  'Social Media Platforms',
  'Streaming Services',
  'Phone Brands',
  'Fast Food Chains',
  'Grocery Store Chains',
  'Sports Brands',
  'Websites',
  'Famous Logos',

  // ── Music & Performance ────────────────────────
  'Musical Instruments',
  'Types of Dances',
  'Music Genres',
  'Songs You Sing in the Shower',
  'Karaoke Songs',
  'One-Hit Wonders',
  'Love Songs',
  'Sad Songs',
  'Party Songs',
  'Road Trip Songs',
  'Workout Songs',
  'Songs From the 2000s',
  'Songs Everyone Knows',

  // ── Nature & Science ───────────────────────────
  'Things in Outer Space',
  'Things in the Ocean',
  'Dog Breeds',
  'Cat Breeds',
  'Mythical Creatures',
  'Types of Weather',
  'Dinosaurs',
  'Things That Fly',
  'Things That Grow',
  'Bodies of Water',
  'Birds',
  'Fish',
  'Reptiles',
  'Zoo Animals',
  'Farm Animals',
  'Baby Animals',
  'Animals That Swim',
  'Nocturnal Animals',
  'Endangered Species',
  'Types of Clouds',
  'Constellations',
  'Planets or Moons',
  'Rocks or Minerals',
  'Things in a Forest',
  'Things in a Garden',
  'Sea Creatures',
  'Jungle Animals',
  'Desert Animals',

  // ── Specific Locations / Scenes ────────────────
  'Things at a Beach',
  'Things in a Fridge',
  'Things at a Wedding',
  'Things at a Gym',
  'Things on a Farm',
  'Things at a Hospital',
  'Things at an Airport',
  'Things at a Concert',
  'Things at a Carnival',
  'Things on a Road Trip',
  'Things at a Sleepover',
  'Things at a Barbecue',
  'Things at a Birthday Party',
  'Things at a Baby Shower',
  'Things in a Hotel Room',
  'Things at a Movie Theater',
  'Things at a Bowling Alley',
  'Things at a Gas Station',
  'Things at a Laundromat',
  'Things at a Campsite',
  'Things at a Garage Sale',
  'Things at a Playground',
  'Things in a Locker Room',
  'Things at a Food Court',
  'Things at a Petting Zoo',
  'Things at a Water Park',
  'Things at a Farmers Market',
  'Things at a Haunted House',
  'Things at a Spa',
  'Things at a Library',
  'Things at a Museum',
  'Things at a Casino',
  'Things in a Kitchen',
  'Things in a Bathroom',
  'Things in a Bedroom',
  'Things in a Garage',
  'Things in a Living Room',
  'Things in a Basement',
  'Things in an Attic',
  'Things in a Closet',

  // ── Objects & Stuff ────────────────────────────
  'Things Made of Wood',
  'Things That Come in Pairs',
  'Things You Plug In',
  'Things That Bounce',
  'Things You Open',
  'Things You Lose',
  'Things in Your Junk Drawer',
  'Things in a Toolbox',
  'Things in a Backpack',
  'Things in Your Pockets',
  'Things That Need Batteries',
  'Vehicles',
  'Types of Shoes',
  'Types of Hats',
  'Things on a Desk',
  'Things on a Keychain',
  'Things in a Wallet',
  'Things in a Purse',
  'Things in a Suitcase',
  'Things That Have Wheels',
  'Things With Buttons',
  'Things You Hang on a Wall',
  'Things You Find Under the Couch',
  'Things in a Vending Machine',
  'Things That Have Handles',
  'Kitchen Utensils',
  'Tools',
  'Weapons in a Video Game',
  'Things in a Medicine Cabinet',
  'Things in a Glove Box',
  'Things in a Lunch Box',
  'Things That Tick',
  'Things That Beep',
  'Things With Screens',

  // ── Sports & Games ─────────────────────────────
  'Olympic Sports',
  'Team Sports',
  'Individual Sports',
  'Water Sports',
  'Winter Sports',
  'Sports Equipment',
  'Sports Teams',
  'Famous Athletes',
  'Gym Exercises',
  'Yoga Poses',
  'Martial Arts',
  'Extreme Sports',
  'Sports Stadiums',
  'Sports Rules Everyone Gets Wrong',
  'Playground Games',

  // ── Fashion & Appearance ───────────────────────
  'Types of Jackets',
  'Accessories',
  'Hairstyles',
  'Types of Pants',
  'Things You Wear to a Formal Event',
  'Halloween Costumes',
  'Things People Wear at the Beach',
  'Types of Bags',
  'Jewelry',
  'Patterns on Clothing',

  // ── Around the House ───────────────────────────
  'Household Chores',
  'Things That Need Cleaning',
  'Things You Find in a Junk Drawer',
  'Types of Rooms',
  'Home Appliances',
  'Things on a Grocery List',
  'Things You Throw Away',
  'Things You Recycle',
  'Things That Break Easily',
  'Things You Fix With Duct Tape',
  'Things Under the Sink',
  'Things on a Shelf',

  // ── Travel & Transportation ────────────────────
  'Airlines',
  'Things You Pack',
  'Road Trip Essentials',
  'Things You See on a Highway',
  'Types of Boats',
  'Types of Trains',
  'Things You Do on a Plane',
  'Vacation Destinations',
  'Souvenirs',
  'Things You Need a Passport For',
  'Camping Gear',
  'Travel Snacks',

  // ── Random / Fun ───────────────────────────────
  'Things That Are Overpriced',
  'Things You\'d Find in a Time Capsule',
  'Things a Pirate Would Say',
  'Things You\'d Name a Band',
  'Things on a Bucket List',
  'Things in a Treasure Chest',
  'Superstitions',
  'Things You\'d Wish For',
  'Things Grandma Would Say',
  'Things a Toddler Would Say',
  'Famous Last Words',
  'Things Written on T-Shirts',
  'Bumper Sticker Sayings',
  'Things You\'d Find in a Haunted House',
  'Things a Robot Would Say',
  'Things You\'d Take Into Space',
  'Conspiracy Theories',
  'Things You\'d Find at Hogwarts',
  'Inventions We Still Need',
  'Things That Don\'t Exist But Should',
  'Things You Shouldn\'t Do at Work',
  'Terrible Gift Ideas',
  'Things a Cat Would Say If It Could Talk',
  'Things on a Chalkboard Menu',
  'Things That Come in a Box',
  'Excuses for Not Doing Homework',
  'Things You\'d Find in a Lost and Found',
  'Weird Laws',
  'Things That Are Better Homemade',
  'Things That Are Better Store-Bought',
  'Things You Learn the Hard Way',
  'Things Everyone Pretends to Understand',
  'Things You Can\'t Do Quietly',
  'Unwritten Rules',
  'Things That Were Better in the 90s',
  'Things That Didn\'t Exist 20 Years Ago',
];

export function pickCategories(count: number): string[] {
  const shuffled = [...ALL_CATEGORIES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
